# -*- coding: utf-8 -*-
"""Temporary update script - inject 05/19 data into player_props_dispatch.py"""

NEW_DATA = '''BATTING_PROPS = [
    {"player": "Alec Bohm", "team": "PHI", "opp": "CIN",
     "prop": "Hits", "line": "o0.5", "odds": "-242",
     "matchupEdge": "Bohm vs CIN (9-game hit streak, 100% H2H)", "streak": "9",
     "pick": "OVER 0.5", "confidence": "95%",
     "rationale": "[LOCK] 9-game hit streak. 100% H2H vs CIN. 55% 2026 rate. Parlay anchor."},
    {"player": "Samuel Basallo", "team": "BAL", "opp": "TB",
     "prop": "Hits", "line": "o0.5", "odds": "-173",
     "matchupEdge": "Basallo vs TB (10-game hit streak)", "streak": "10",
     "pick": "OVER 0.5", "confidence": "94%",
     "rationale": "[LOCK] 10-game hit streak. 65% 2026 rate. Longest active streak on the board."},
    {"player": "Spencer Steer", "team": "CIN", "opp": "PHI",
     "prop": "Hits", "line": "o0.5", "odds": "-185",
     "matchupEdge": "Steer vs PHI (9-game hit streak, 57% H2H)", "streak": "9",
     "pick": "OVER 0.5", "confidence": "93%",
     "rationale": "[LOCK] 9-game hit streak. 72% 2026 rate. 57% H2H vs PHI."},
    {"player": "Jake Bauers", "team": "MIL", "opp": "CHC",
     "prop": "Hits", "line": "o0.5", "odds": "-161",
     "matchupEdge": "Bauers vs CHC (9-game hit streak, 67% H2H)", "streak": "9",
     "pick": "OVER 0.5", "confidence": "91%",
     "rationale": "[LOCK] 9-game streak. 67% 2026 rate. 67% H2H vs CHC."},
    {"player": "Yandy Diaz", "team": "TB", "opp": "BAL",
     "prop": "Hits", "line": "o0.5", "odds": "-275",
     "matchupEdge": "Diaz vs BAL (5-game streak, 92% H2H)", "streak": "5",
     "pick": "OVER 0.5", "confidence": "89%",
     "rationale": "77% 2026 rate. 92% H2H vs BAL. One of the highest H2H rates on the board."},
    {"player": "Ivan Herrera", "team": "STL", "opp": "PIT",
     "prop": "Hits", "line": "o0.5", "odds": "-243",
     "matchupEdge": "Herrera vs PIT (6-game streak, 86% H2H)", "streak": "6",
     "pick": "OVER 0.5", "confidence": "88%",
     "rationale": "76% 2026 rate. 86% H2H vs PIT. Elite contact form."},
    {"player": "Angel Martinez", "team": "CLE", "opp": "DET",
     "prop": "Hits", "line": "o0.5", "odds": "-230",
     "matchupEdge": "Martinez vs DET (7-game streak, 79% H2H)", "streak": "7",
     "pick": "OVER 0.5", "confidence": "87%",
     "rationale": "7-game streak. 79% H2H vs DET. Consistent contact presence."},
    {"player": "Travis Bazzana", "team": "CLE", "opp": "DET",
     "prop": "Hits", "line": "o0.5", "odds": "-212",
     "matchupEdge": "Bazzana vs DET (5-game streak, 100% H2H)", "streak": "5",
     "pick": "OVER 0.5", "confidence": "86%",
     "rationale": "100% H2H vs DET. 67% 2026 rate. Strong value at this price."},
    {"player": "Juan Soto", "team": "NYM", "opp": "WSH",
     "prop": "Runs", "line": "o0.5", "odds": "-128",
     "matchupEdge": "Soto vs WSH (5-game run streak, 77% H2H)", "streak": "5",
     "pick": "OVER 0.5", "confidence": "84%",
     "rationale": "5-game streak. 77% H2H vs WSH. 47% 2026 run rate. Excellent leadoff value."},
    {"player": "Bryce Harper", "team": "PHI", "opp": "CIN",
     "prop": "Runs", "line": "o0.5", "odds": "-128",
     "matchupEdge": "Harper vs CIN (4-game run streak, A- grade)", "streak": "4",
     "pick": "OVER 0.5", "confidence": "83%",
     "rationale": "4-game run streak. 51% 2026 rate. A- matchup grade vs CIN."},
]

# ============================================================
#  PITCHING PROPS — 05/19/2026
# ============================================================
PITCHING_PROPS = [
    {"player": "Nolan McLean", "team": "NYM", "opp": "WSH",
     "prop": "Strikeouts", "line": "o5.5", "odds": "-229",
     "matchupEdge": "McLean vs WSH (7-K streak, 100% H2H, B grade)", "streak": "7",
     "pick": "OVER 5.5", "confidence": "96%",
     "rationale": "[LOCK] 89% 2026 rate. 88% 2025 rate. 7-game K streak. 100% H2H vs WSH."},
    {"player": "Parker Messick", "team": "CLE", "opp": "DET",
     "prop": "Strikeouts", "line": "o5.5", "odds": "-140",
     "matchupEdge": "Messick vs DET (4-K streak, 100% H2H, B+ grade)", "streak": "4",
     "pick": "OVER 5.5", "confidence": "93%",
     "rationale": "[LOCK] 67% 2026 rate. 100% H2H vs DET. 4-game K streak."},
    {"player": "Dylan Cease", "team": "TOR", "opp": "NYY",
     "prop": "Strikeouts", "line": "o7.5", "odds": "-112",
     "matchupEdge": "Cease vs NYY (100% H2H, A- grade)", "streak": "2",
     "pick": "OVER 7.5", "confidence": "91%",
     "rationale": "[LOCK] 100% H2H vs NYY. 56% 2026 rate. High line, but H2H is perfect."},
    {"player": "Emmet Sheehan", "team": "LAD", "opp": "SD",
     "prop": "Strikeouts", "line": "o5.5", "odds": "-128",
     "matchupEdge": "Sheehan vs SD (4-K streak, 100% H2H, B- grade)", "streak": "4",
     "pick": "OVER 5.5", "confidence": "88%",
     "rationale": "75% 2026 rate. 100% H2H vs SD. 4-game K streak. Reliable."},
    {"player": "Will Warren", "team": "NYY", "opp": "TOR",
     "prop": "Strikeouts", "line": "o5.5", "odds": "+117",
     "matchupEdge": "Warren vs TOR (6-K streak, B- grade)", "streak": "6",
     "pick": "OVER 5.5", "confidence": "85%",
     "rationale": "78% 2026 rate. 6-game K streak. Plus-money (+117) on a pitcher this hot is elite value."},
    {"player": "Jacob Misiorowski", "team": "MIL", "opp": "CHC",
     "prop": "Strikeouts", "line": "o7.5", "odds": "+114",
     "matchupEdge": "Misiorowski vs CHC (5-K streak, B+ grade)", "streak": "5",
     "pick": "OVER 7.5", "confidence": "82%",
     "rationale": "78% 2026 rate. 5-game K streak. Plus-money at +114 on elite whiff rate."},
    {"player": "Jesus Luzardo", "team": "PHI", "opp": "CIN",
     "prop": "Strikeouts", "line": "o6.5", "odds": "-140",
     "matchupEdge": "Luzardo vs CIN (+0.3 edge score, B grade)", "streak": "0",
     "pick": "OVER 6.5", "confidence": "80%",
     "rationale": "56% 2026 rate. +0.3 edge score. Strong matchup advantage vs CIN bats."},
]

# ============================================================
#  ALTERNATE BATTING PROPS — 100% Hit Rate Cheatsheet 05/19/2026
# ============================================================
ALT_BATTING_PROPS = [
    {"player": "M. Garcia", "team": "NYY", "opp": "BOS",
     "prop": "H+R+RBI", "line": "o0.5", "odds": "-385",
     "matchupEdge": "12/L12 — Supreme Lock", "streak": "12",
     "pick": "OVER 0.5", "confidence": "99%",
     "rationale": "[SUPREME LOCK] 12/12 last 12 games. Longest 100% streak on the board."},
    {"player": "E. De La Cruz", "team": "CIN", "opp": "PHI",
     "prop": "H+R+RBI", "line": "o0.5", "odds": "-250",
     "matchupEdge": "11/L11 — Lock", "streak": "11",
     "pick": "OVER 0.5", "confidence": "99%",
     "rationale": "[LOCK] 11/11. Elly is on fire heading into PHI."},
    {"player": "E. De La Cruz", "team": "CIN", "opp": "PHI",
     "prop": "Total Bases", "line": "o0.5", "odds": "-215",
     "matchupEdge": "10/L10 — Lock", "streak": "10",
     "pick": "OVER 0.5", "confidence": "99%",
     "rationale": "[LOCK] 10/10 Total Bases. Near-automatic parlay piece."},
    {"player": "K. Griffin", "team": "PIT", "opp": "STL",
     "prop": "H+R+RBI", "line": "o0.5", "odds": "-362",
     "matchupEdge": "9/L9 — Lock", "streak": "9",
     "pick": "OVER 0.5", "confidence": "99%",
     "rationale": "[LOCK] 9/9. High juice but mathematically near-certain."},
    {"player": "J. Bauers", "team": "MIL", "opp": "CHC",
     "prop": "H+R+RBI", "line": "o0.5", "odds": "-225",
     "matchupEdge": "9/L9 — Lock", "streak": "9",
     "pick": "OVER 0.5", "confidence": "99%",
     "rationale": "[LOCK] 9/9. Bauers hitting in every game this stretch."},
    {"player": "A. Bohm", "team": "PHI", "opp": "CIN",
     "prop": "H+R+RBI", "line": "o0.5", "odds": "-250",
     "matchupEdge": "8/L8 — Lock", "streak": "8",
     "pick": "OVER 0.5", "confidence": "99%",
     "rationale": "[LOCK] 8/8. PHI lineup producing every night."},
    {"player": "S. Steer", "team": "CIN", "opp": "PHI",
     "prop": "H+R+RBI", "line": "o0.5", "odds": "-247",
     "matchupEdge": "8/L8 — Lock", "streak": "8",
     "pick": "OVER 0.5", "confidence": "99%",
     "rationale": "[LOCK] 8/8. Steer is an automatic H+R+RBI machine right now."},
    {"player": "W. Warren", "team": "NYY", "opp": "TOR",
     "prop": "Strikeouts", "line": "o3.5", "odds": "-400",
     "matchupEdge": "8/L8 K streak — Lock", "streak": "8",
     "pick": "OVER 3.5", "confidence": "99%",
     "rationale": "[LOCK] 8/8. Warren strikes out 3+ in every recent start."},
    {"player": "B. Baty", "team": "NYM", "opp": "WSH",
     "prop": "H+R+RBI", "line": "o0.5", "odds": "-215",
     "matchupEdge": "6/L6 — Lock", "streak": "6",
     "pick": "OVER 0.5", "confidence": "99%",
     "rationale": "[LOCK] 6/6. NYM offense rolling, Baty contributing every night."},
    {"player": "J. Soto", "team": "NYM", "opp": "WSH",
     "prop": "H+R+RBI", "line": "o0.5", "odds": "-400",
     "matchupEdge": "4/L4 — Lock", "streak": "4",
     "pick": "OVER 0.5", "confidence": "99%",
     "rationale": "[LOCK] 4/4. Soto is the anchor. Heavy juice but automatic."},
]
'''

content = open(r'H:\Trishula\Swarm_4_Integration\Salvo_Staging\player_props_dispatch.py', encoding='utf-8').read()
start = content.find('BATTING_PROPS = [')
end = content.find('\ndef chunk(lst, n):')
replacement = content[:start] + NEW_DATA + content[end:]
open(r'H:\Trishula\Swarm_4_Integration\Salvo_Staging\player_props_dispatch.py', 'w', encoding='utf-8').write(replacement)
print(f'Done. File written: {len(replacement)} chars.')
